name: Rust Plain

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt update && sudo apt install --assume-yes cmake protobuf-compiler

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: actions/checkout@v3

      - name: Rust cache
        uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0

      - run:  cargo test --workspace --features runtime-benchmarks
