name: Rust Plain

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - run: sudo apt update && sudo apt install --assume-yes cmake protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/checkout@v3
      - run:  cargo test --workspace --features runtime-benchmarks
